// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-sXhiLLswhHoWObsL5wu_pfc35LYwQOw',
    appId: '1:145463372803:web:613725b3c595e4ab943236',
    messagingSenderId: '145463372803',
    projectId: 'notesapp-2d9f3',
    authDomain: 'notesapp-2d9f3.firebaseapp.com',
    storageBucket: 'notesapp-2d9f3.firebasestorage.app',
    measurementId: 'G-RT4MK6BE6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd_jJanUbg5woFSlqf82p9pB5QKOW0AUg',
    appId: '1:145463372803:android:8a740a07ade51b47943236',
    messagingSenderId: '145463372803',
    projectId: 'notesapp-2d9f3',
    storageBucket: 'notesapp-2d9f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGXMeddMg_SwWzNalbdIC89Nbt6cbRjOQ',
    appId: '1:145463372803:ios:c8163b7dfcbbf5ea943236',
    messagingSenderId: '145463372803',
    projectId: 'notesapp-2d9f3',
    storageBucket: 'notesapp-2d9f3.firebasestorage.app',
    iosBundleId: 'com.example.secureNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGXMeddMg_SwWzNalbdIC89Nbt6cbRjOQ',
    appId: '1:145463372803:ios:c8163b7dfcbbf5ea943236',
    messagingSenderId: '145463372803',
    projectId: 'notesapp-2d9f3',
    storageBucket: 'notesapp-2d9f3.firebasestorage.app',
    iosBundleId: 'com.example.secureNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-sXhiLLswhHoWObsL5wu_pfc35LYwQOw',
    appId: '1:145463372803:web:c2a75217292719f0943236',
    messagingSenderId: '145463372803',
    projectId: 'notesapp-2d9f3',
    authDomain: 'notesapp-2d9f3.firebaseapp.com',
    storageBucket: 'notesapp-2d9f3.firebasestorage.app',
    measurementId: 'G-BSMJN0596E',
  );

}